# Shield AI — Next.js frontend image (Cloud Run production)
#
# Build args:
#   NEXT_PUBLIC_BACKEND_URL — Cloud Run backend URL, baked in at build time.
#                             Defaults to the known shield-backend Cloud Run URL.
#                             Override via --build-arg or cloudbuild.yaml substitution.
#
# Multi-stage build:
#   1. deps    — install node_modules (cached layer)
#   2. builder — next build with standalone output
#   3. runner  — minimal alpine image (~150 MB vs ~1 GB full install)

# ── Stage 1: install deps ──────────────────────────────────────────────────────
FROM node:20-alpine AS deps
WORKDIR /app

# Copy only package files first so this layer is cached unless deps change
COPY frontend-next/package.json frontend-next/package-lock.json ./
RUN npm ci

# ── Stage 2: build ────────────────────────────────────────────────────────────
FROM node:20-alpine AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY frontend-next/ .

# NEXT_PUBLIC_ vars are inlined at build time by Next.js (not available at runtime)
ARG NEXT_PUBLIC_BACKEND_URL=https://shield-backend-aiffxvrl4q-uc.a.run.app
ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

RUN npm run build

# ── Stage 3: production runner ────────────────────────────────────────────────
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV NEXT_TELEMETRY_DISABLED=1

# Non-root user
RUN addgroup --system --gid 1001 nodejs && \
    adduser  --system --uid 1001 nextjs

# Copy built output from builder
# standalone/ is self-contained — no node_modules install needed
COPY --from=builder /app/public                    ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static     ./.next/static

USER nextjs
EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
    CMD wget -qO- http://localhost:3000/ || exit 1

# server.js is generated by Next.js standalone output
CMD ["node", "server.js"]
